name: PSCMake CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - 'README.md'
  workflow_dispatch:
jobs:
  run-pester-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Invoke-Pester
        shell: pwsh
        run: |
          Import-Module Pester
          $Configuration = [PesterConfiguration]@{
            Run = @{
              Path = '*'
              Passthru = $true
            }
            CodeCoverage = @{
              Enabled = $true
            }
          }
          Invoke-Pester -Configuration $Configuration