name: PSCMake PullRequest
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Invoke-Pester
        shell: pwsh
        run: |
          Import-Module Pester
          $Configuration = [PesterConfiguration]@{
            Run = @{
              Path = '*'
              Passthru = $true
            }
            CodeCoverage = @{
              Enabled = $true
              OutputFormat = 'JaCoCo'
              OutputPath = '${{ env.GITHUB_WORKSPACE }}/Pester-Coverage.xml'
            }
          }
          Invoke-Pester -Configuration $Configuration
      - name: Build
        shell: pwsh
        run: |
          & .\Build\Publish.ps1 -Verbose
      - name: Upload __packages
        uses: actions/upload-artifact@v3
        with:
          name: __packages
          path: __packages
