name: PullRequest
on: [pull_request,workflow_dispatch]
jobs:
  run-pester-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Invoke-Pester
        shell: pwsh
        run: Invoke-Pester -Passthru
